#!/bin/bash
#
#   ConVirt   -  Copyright (c) 2008 Convirture Corp.
#   ======
#
# ConVirt is a Virtualization management tool with a graphical user
# interface that allows for performing the standard set of VM operations
# (start, stop, pause, kill, shutdown, reboot, snapshot, etc...). It
# also attempts to simplify various aspects of VM lifecycle management.
#
#
# This software is subject to the GNU General Public License, Version 2 (GPLv2)
# and for details, please consult it at:
#
#    http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
# 
#
# author : Jd <jd_jedi@users.sourceforge.net>
#

# Distribution and version specific code can go here.
# Assume that common functions are included
# Assme the DIST and the VER to be set here.

source $common_install_scripts/Debian_functions

install_cms_prereq_packages()
{
   xen_deps="python-xen-3.3 libxen3"

   if [ "$VER" == "12.04" ]; then
      xen_deps="xen-utils-4.1 libxenstore3.0"
   fi

   $SUDO apt-get install -y python-dev build-essential python-paramiko ssh $xen_deps socat uml-utilities dnsmasq wget mysql-server
   ret=$?
   if [ $ret != 0 ]; then
      echo "ERROR: installing CMS Prerequisites."
      return $ret
   fi

   if [ "$VER" == "9.10" ]; then
      $SUDO apt-get install -y libmysqlclient15-dev
   elif [ "$VER" == "10.04" ] || [ "$VER" == "10.10" ]; then
      $SUDO apt-get install -y libmysqlclient-dev
   elif [ "$VER" == "12.04" ]; then
      $SUDO apt-get install -y libmysqlclient-dev python2.7-dev python-setuptools 
   fi
   if [ $ret != 0 ]; then
      echo "ERROR: installing additional CMS Prerequisites."
      return $ret
   fi
}
  

fix_xen_in_tg2env()
{
   # Link xen libraries
   if [ "$VER" == "12.04" ]; then
      ln -s /usr/lib/xen-4.1/lib/python/xen $VIRTUAL_ENV_DIR/lib/python2.7/site-packages/
      ln -s /usr/lib/xen-4.1/lib/python/xen-3.0.egg-info $VIRTUAL_ENV_DIR/lib/python2.7/site-packages/
   else
      ln -s /usr/lib/python2.5/site-packages/xen $VIRTUAL_ENV_DIR/lib/python2.6/site-packages/
      ln -s /usr/lib/python2.5/site-packages/xen-3.0.egg-info $VIRTUAL_ENV_DIR/lib/python2.6/site-packages/
   fi
}
