ALTER TABLE `deployment` ADD COLUMN `cms_started` DATETIME  DEFAULT NULL,
 ADD COLUMN `cms_deployed` DATETIME  DEFAULT NULL,
 ADD COLUMN `cms_end` DATETIME  DEFAULT NULL,
 ADD COLUMN `xen_server` INTEGER  DEFAULT 0,
 ADD COLUMN `kvm_server` INTEGER  DEFAULT 0,
 ADD COLUMN `sps` INTEGER  DEFAULT 0,
 ADD COLUMN `vms` INTEGER  DEFAULT 0,
 ADD COLUMN `templates` INTEGER  DEFAULT 0,
 ADD COLUMN `users` INTEGER  DEFAULT 0,
 ADD COLUMN `storages` INTEGER  DEFAULT 0,
 ADD COLUMN `networks` INTEGER  DEFAULT 0;

