#!/bin/bash

upgrade_config()
{
  upgrade_base=$1
  dev_ini=$2

  echo "Upgrading $dev_ini from 2.0.2-2.1"
  sed  -i "

/UPDATE_DISK_SIZE_INTERVAL=60/ { i\
update_from_version=2.0.2\n\
NOTIFICATION_COUNT=500\n\
TASK_PURGE_COUNT=5000
}
/max_ping_servers/ {s/2/10/}

/max_ping_workers/ {s/2/5/}

/completion_time=2/ { a\
max_worker_wait_time=300\n\
max_node_avail_wait_time=45\n\
max_vm_avail_wait_time=60\n\
max_node_metrics_wait_time=90
}

/enable_stack_trace_url=True/ { i\
enable_used_ports_url=True

}

/qualname = convirt/  { a\
[logger_STORAGE_TIMING]\n\
level = WARN\n\
handlers = rotating\n\
qualname = STORAGE_TIMING\n\
[logger_AVAIL_TIMING]\n\
level = WARN\n\
handlers = rotating\n\
qualname = AVAIL_TIMING\n\
[logger_METRICS_TIMING]\n\
level = WARN\n\
handlers = rotating\n\
qualname = METRICS_TIMING\n\
[logger_WORKER]\n\
level = WARN\n\
handlers = rotating\n\
qualname = WORKER

}
/vnc_password=/ {a\
ssh_forwarder = localhost\n\
ssh_forwarder_port_range = 6900:6999\n\
ssh_forwarder_user = \n\
ssh_forwarder_password = \n\
# Set True or False \n\
ssh_forwarder_use_keys=False \n\
ssh_forwarder_tunnel_setup = False
}
/vnc_applet_param_offer_relogin=No/ {a\
# vnc_log_level value from 0 to 4\n\
vnc_log_level=3\n\
ssh_log_level=3
}

/keys = root, convirt, sqlalchemy, auth,/ {s/tgi18n/tgi18n,AVAIL_TIMING, STORAGE_TIMING, METRICS_TIMING, WORKER/}

/# 2.0.1+ packaging/ {a\
ssh_cmd  =  xterm -hold -e ssh -p \$PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \$USER@\$IP\n\
putty_cmd = putty -P \$PORT \$USER@\$IP
}

" $dev_ini
  if [ $? != 0 ]; then 
     return 1
  fi
  return 0
}
