#!/bin/bash
#
#   ConVirt   -  Copyright (c) 2008 Convirture Corp.
#   ======
#
# ConVirt is a Virtualization management tool with a graphical user
# interface that allows for performing the standard set of VM operations
# (start, stop, pause, kill, shutdown, reboot, snapshot, etc...). It
# also attempts to simplify various aspects of VM lifecycle management.
#
#
# This software is subject to the GNU General Public License, Version 2 (GPLv2)
# and for details, please consult it at:
#
#    http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
# 
#
# author : Jd <jd_jedi@users.sourceforge.net>
#

# Distribution and version specific code can go here.
# Assume that common functions are included
# Assme the DIST and the VER to be set here.



install_cms_prereq_packages()
{
  $SUDO apt-get install -y python-dev build-essential python-paramiko ssh xen-utils socat uml-utilities dnsmasq wget mysql-server libmysqlclient15-dev
}

set_default_to_innodb()
{
   # Make the innodb default engine
   $SUDO sh -c "cat <<EOF > /etc/mysql/conf.d/config.cnf
[mysqld]
default-storage-engine=innodb
EOF
"
}

