#!/bin/bash
#
#   ConVirt   -  Copyright (c) 2008 Convirture Corp.
#   ======
#
# ConVirt is a Virtualization management tool with a graphical user
# interface that allows for performing the standard set of VM operations
# (start, stop, pause, kill, shutdown, reboot, snapshot, etc...). It
# also attempts to simplify various aspects of VM lifecycle management.
#
#
# This software is subject to the GNU General Public License, Version 2 (GPLv2)
# and for details, please consult it at:
#
#    http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
# 
#
# author : Jd <jd_jedi@users.sourceforge.net>
#

prg_name=`readlink -f $0`
base=`dirname $prg_name`
if [ "${base}" == "" ]; then
    base="."
fi
common_scripts=${base}/../../../common/scripts
common_install_scripts=${base}/../common

source $common_scripts/functions
source $common_install_scripts/functions

# detect distro
detect_distro

if [ "$?" != "0" ]; then
   echo "Error detecting Linux distribution.Exiting."
   exit 1
fi

# dump information
echo "DISTRO ${DIST}"
echo "VER ${VER}"
echo "CODENAME ${CODE_NAME}"
echo "KERNEL ${KERNEL}"
echo "ARCH ${ARCH}"

#include the distro specific file if it exists.
distro_functions=$common_scripts/${DIST}_functions
if [ -r $distro_functions ]; then
    echo "Info: Sourcing $distro_functions"
    source $distro_functions
else
   echo "Info: $distro_functions not found."
fi

#include the distro specific file if it exists.
distro_install_functions=$common_install_scripts/${DIST}_functions
if [ -r $distro_install_functions ]; then
    echo "Info: Sourcing $distro_install_functions"
    source $distro_install_functions
else
   echo "Info: $distro_install_functions not found."
fi

source $base/install_config

# TBD: add some command line parsing.. and checks

create_tg2env
if [ "$?" != "0" ]; then
   echo "ERROR: Failed creating Turbogears2 environment."
   exit 1
else
   echo "TurboGears environmnet setup successfully."
fi

